import type {ReactNode} from 'react';
import Layout from '@theme/Layout';
import BrowserOnly from '@docusaurus/BrowserOnly';
import spec from '@site/asyncapi/asyncapi.json';
import '@asyncapi/react-component/styles/default.min.css';
import './websocket-api.dark.css';

// The AsyncAPI spec is generated by audiaptic-server and synced here by its
// api-docs-sync workflow, the same way openapi/openapi.json is.

const config = {
  show: {
    sidebar: true,
    // Messages are already listed under the operation that sends them;
    // the flat list would mix events and acks together.
    messages: false,
  },
  sidebar: {
    // List operations directly. 'byOperationsTags' groups them per socket via
    // their tags, but starts every group collapsed; worth it once the
    // audience socket exists.
    showOperations: 'byDefault',
  },
  // AsyncAPI actions are from the server's point of view, which reads
  // backwards to someone writing a client, so label by direction instead.
  receiveLabel: 'CLIENT → SERVER',
  sendLabel: 'SERVER → CLIENT',
};

export default function WebSocketApi(): ReactNode {
  return (
    <Layout title="WebSocket API" description="Performer WebSocket events and acks">
      <BrowserOnly fallback={<div>Loading…</div>}>
        {() => {
          // Loaded only in the browser: the component touches `window`,
          // which doesn't exist during Docusaurus's server-side build.
          // The prebuilt browser bundle is used because the default entry
          // pulls in Node built-ins (util, crypto, ...) webpack can't resolve.
          const mod = require('@asyncapi/react-component/browser/index.js');
          const AsyncApiComponent = mod.default ?? mod;
          return <AsyncApiComponent schema={spec} config={config} />;
        }}
      </BrowserOnly>
    </Layout>
  );
}
